baseURL = 'https://spencergreenhalgh.com/'
languageCode = 'en-us'
title = 'Spencer Greenhalgh'
theme = "ananke_custom"
# themesDir = "../.."
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 36 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Spencer Greenhalgh"
  text_color = ""
  author = ""
  favicon = "/SPG_4_circle.png"
  site_logo = "/SPG_4_circle.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = ""
  recent_posts_number = 2

[[params.ananke_socials]]
name = "rss"
url = "/rss"
[[params.ananke_socials]]
name = "scholar"
url = "https://scholar.google.com/citations?user=o3JQjpcAAAAJ&hl=en&oi=sra"
[[params.ananke_socials]]
name = "microdotblog"
url = "https://micro.blog/spgreenhalgh"
[[params.ananke_socials]]
name = "mastodon"
url = "/mastodon"
[[params.ananke_socials]]
name = "keybase"
url = "https://keybase.io/spgreenhalgh"
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/spgreenhalgh"


